[build]
  command = "cp -r ../hysteriahighest hhighest"
  publish = "."
  ignore  = "exit 0"

# Czyste URL-e — darkgraal3
[[redirects]]
  from = "/gmpanel"
  to   = "/gmpanel.html"
  status = 200

# Czyste URL-e — Hysteria Highest
[[redirects]]
  from = "/hhighest/gmpanel"
  to   = "/hhighest/gmpanel.html"
  status = 200
